import { codeBlock } from 'common-tags';
import type { StatusResult } from 'simple-git';
import upath from 'upath';
import { mockDeep } from 'vitest-mock-extended';
import { envMock, mockExecAll, mockExecSequence } from '~test/exec-util.ts';
import { env, fs, git, hostRules, partial } from '~test/util.ts';
import { GlobalConfig } from '../../../config/global.ts';
import type { RepoGlobalConfig } from '../../../config/types.ts';
import type { UpdateArtifactsConfig } from '../types.ts';
import { updateArtifacts } from './index.ts';

vi.mock('../../../util/exec/env.ts');
vi.mock('../../../util/fs/index.ts');
vi.mock('../../../util/host-rules.ts', () => mockDeep());

const adminConfig: RepoGlobalConfig = {
  // `join` fixes Windows CI
  localDir: upath.join('/tmp/github/some/repo'),
  cacheDir: upath.join('/tmp/renovate/cache'),
  binarySource: 'global',
};

const config: UpdateArtifactsConfig = {};

const packageFileName = '.github/workflows/release.yml';
const lockFileName = '.github/workflows/actions.lock';

const workflowContent = codeBlock`
  jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6.0.3
`;

const lockFileContent = codeBlock`
  # This file is machine-generated by \`gh actions-lock\`.
  # Do not edit by hand; run \`gh actions-lock\` to update.
  version: 'v0.0.2'
  workflows:
      '.github/workflows/release.yml':
          - 'actions/checkout@v6.0.2'
  dependencies:
      'actions/checkout@v6.0.2':
          ref: 'v6.0.2'
          commit: 'sha1-de0fac2e4500dabe0009e67214ff5f5447ce83dd'
          owner_id: 44036562
          repo_id: 197814629
`;

const updatedDeps = [
  {
    depName: 'actions/checkout',
    depType: 'action',
    currentValue: 'v6.0.2',
    newValue: 'v6.0.3',
  },
];

describe('modules/manager/github-actions/artifacts', () => {
  beforeEach(() => {
    env.getChildProcessEnv.mockReturnValue(envMock.basic);
    GlobalConfig.set(adminConfig);
    hostRules.find.mockReturnValue({ token: undefined });
  });

  it('returns null if no actions.lock found', async () => {
    fs.readLocalFile.mockResolvedValueOnce(null);
    const execSnapshots = mockExecAll();

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toBeNull();
    expect(execSnapshots).toEqual([]);
  });

  it('returns null if actions.lock cannot be parsed', async () => {
    fs.readLocalFile.mockResolvedValueOnce('invalid: [yaml');
    const execSnapshots = mockExecAll();

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toBeNull();
    expect(execSnapshots).toEqual([]);
  });

  it('returns null if the workflow is not onboarded to actions.lock', async () => {
    fs.readLocalFile.mockResolvedValueOnce(lockFileContent);
    const execSnapshots = mockExecAll();

    const res = await updateArtifacts({
      packageFileName: '.github/workflows/other.yml',
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toBeNull();
    expect(execSnapshots).toEqual([]);
  });

  it('updates the lock file for local composite actions', async () => {
    fs.readLocalFile
      .mockResolvedValueOnce(lockFileContent)
      .mockResolvedValueOnce('new lock content' as never);
    const execSnapshots = mockExecAll();
    git.getRepoStatus.mockResolvedValueOnce(
      partial<StatusResult>({
        modified: ['.github/actions/setup/action.yml', lockFileName],
      }),
    );

    const res = await updateArtifacts({
      packageFileName: '.github/actions/setup/action.yml',
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toEqual([
      {
        file: {
          type: 'addition',
          path: lockFileName,
          contents: 'new lock content',
        },
      },
    ]);
    expect(execSnapshots).toMatchObject([{ cmd: 'gh actions-lock' }]);
  });

  it('returns null if no action dependencies were updated', async () => {
    fs.readLocalFile.mockResolvedValueOnce(lockFileContent);
    const execSnapshots = mockExecAll();

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps: [
        { depName: 'ubuntu', depType: 'github-runner' },
        { depName: 'go', depType: 'uses-with' },
      ],
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toBeNull();
    expect(execSnapshots).toEqual([]);
  });

  it('returns null if actions.lock is unchanged', async () => {
    fs.readLocalFile.mockResolvedValueOnce(lockFileContent);
    const execSnapshots = mockExecAll();
    git.getRepoStatus.mockResolvedValueOnce(
      partial<StatusResult>({
        modified: [packageFileName],
      }),
    );

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toBeNull();
    expect(fs.writeLocalFile).toHaveBeenCalledWith(
      packageFileName,
      workflowContent,
    );
    expect(execSnapshots).toMatchObject([{ cmd: 'gh actions-lock' }]);
  });

  it('returns updated actions.lock', async () => {
    fs.readLocalFile
      .mockResolvedValueOnce(lockFileContent)
      .mockResolvedValueOnce('new lock content' as never);
    const execSnapshots = mockExecAll();
    git.getRepoStatus.mockResolvedValueOnce(
      partial<StatusResult>({
        modified: [packageFileName, lockFileName],
      }),
    );

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toEqual([
      {
        file: {
          type: 'addition',
          path: lockFileName,
          contents: 'new lock content',
        },
      },
    ]);
    expect(execSnapshots).toMatchObject([{ cmd: 'gh actions-lock' }]);
  });

  it('passes the GitHub token as GH_TOKEN to gh', async () => {
    hostRules.find.mockReturnValue({ token: 'x-access-token:some-token' });
    fs.readLocalFile
      .mockResolvedValueOnce(lockFileContent)
      .mockResolvedValueOnce('new lock content' as never);
    const execSnapshots = mockExecAll();
    git.getRepoStatus.mockResolvedValueOnce(
      partial<StatusResult>({
        modified: [lockFileName],
      }),
    );

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toHaveLength(1);
    expect(execSnapshots).toMatchObject([
      {
        cmd: 'gh actions-lock',
        options: { env: { GH_TOKEN: 'some-token' } },
      },
    ]);
  });

  it('returns additional files modified by gh actions-lock', async () => {
    fs.readLocalFile
      .mockResolvedValueOnce(lockFileContent)
      .mockResolvedValueOnce('narrowed workflow content' as never)
      .mockResolvedValueOnce('new lock content' as never);
    const execSnapshots = mockExecAll();
    git.getRepoStatus.mockResolvedValueOnce(
      partial<StatusResult>({
        modified: [
          packageFileName,
          '.github/workflows/other.yml',
          lockFileName,
        ],
      }),
    );

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toEqual([
      {
        file: {
          type: 'addition',
          path: '.github/workflows/other.yml',
          contents: 'narrowed workflow content',
        },
      },
      {
        file: {
          type: 'addition',
          path: lockFileName,
          contents: 'new lock content',
        },
      },
    ]);
    expect(execSnapshots).toMatchObject([{ cmd: 'gh actions-lock' }]);
  });

  it('supports lockFileMaintenance', async () => {
    fs.readLocalFile
      .mockResolvedValueOnce(lockFileContent)
      .mockResolvedValueOnce('new lock content' as never);
    const execSnapshots = mockExecAll();
    git.getRepoStatus.mockResolvedValueOnce(
      partial<StatusResult>({
        modified: [lockFileName],
      }),
    );

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps: [],
      newPackageFileContent: workflowContent,
      config: { ...config, isLockFileMaintenance: true },
    });

    expect(res).toEqual([
      {
        file: {
          type: 'addition',
          path: lockFileName,
          contents: 'new lock content',
        },
      },
    ]);
    expect(execSnapshots).toMatchObject([{ cmd: 'gh actions-lock' }]);
  });

  it('returns an artifact error if gh actions-lock fails', async () => {
    fs.readLocalFile.mockResolvedValueOnce(lockFileContent);
    const execSnapshots = mockExecSequence([new Error('installation failed')]);

    const res = await updateArtifacts({
      packageFileName,
      updatedDeps,
      newPackageFileContent: workflowContent,
      config,
    });

    expect(res).toEqual([
      {
        artifactError: {
          fileName: lockFileName,
          stderr: 'installation failed',
        },
      },
    ]);
    expect(execSnapshots).toMatchObject([{ cmd: 'gh actions-lock' }]);
  });
});
